### ISSUE TITLE
Error in handling the file

### ISSUE THREAD

**Issue by Koshijacok** [shaunthom/Recommendation-System#1]
There was an error for me in opening the file. The directory was correct and the dataset is also the same. Could you take a look ?

**Comment by shaunthom** [comment]
safe_read_data <- function(file_path) {
  tryCatch({
    read.delim(file_path, sep = "\t")
  }, error = function(e) {
    cat("Error in reading file:", e$message, "\n")
    return(NULL)
  })
}

Try this @Koshijacok 

It will catch the error
